name: Frappe Semgrep

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  semgrep:
    name: Frappe Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Semgrep
        run: pip install semgrep

      - name: Clone Frappe Rules
        run: git clone https://github.com/frappe/semgrep-rules /tmp/frappe-semgrep-rules

      - name: Run Semgrep Scan
        run: semgrep scan --config=/tmp/frappe-semgrep-rules/rules --error
